version: '3.7'
services:
    database:
        container_name: database_todo_api
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_api
        ports:
            - '3306'

    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: database